app = "tenexlog"            # change if you want a different hostname
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.healthz]
    type = "http"
    port = 8080
    path = "/healthz"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"